# Generated by Django 5.2.9 on 2025-12-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=100)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('session', models.CharField(max_length=20)),
                ('hall_no', models.CharField(max_length=50)),
                ('seat_no', models.CharField(max_length=50)),
                ('password', models.CharField(default='Kite@12345', max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.dataset')),
            ],
        ),
    ]
